language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

jobs:
  include:
    - dist: precise
      php: 5.3
    - dist: trusty
      php: 5.5

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpunit --coverage-text
